### ISSUE TITLE
Integrate a react component into the front end

### ISSUE THREAD

**Issue by flipdazed** [NiluK/gatekeeper#3]
The react component should be a popup that comes up when you click connect wallet

To start with don't bother integrating into `web3.js` just get it working with Web2

# Web3 Mock
Mock the web3 interface by storing two variables:

 - `nft_present` (bool): `True` if NFT is present, else False
 - `nft_state` (bool): reflects the metadata inside the NFT

# States
The react component should be able to host a variety of states:
1. Minting NFT
2. "Checking for NFT" - this is a temporary state while we are waiting to read the NFT metadata. This will in theory not be seen if 
3. "The NFT needs to be True to use 'A Dapp'" - this comes up if `nft_state` is `False`
4. React Component disappears - This occurs when the `nft_state` is `True`. The react component disappears to reveal a Tick image

**Comment by flipdazed** [comment]
got 1.
got 3.
got 4.

**Comment by samwarwick** [comment]
Mocks were not required.
